### ISSUE TITLE
Plugins start late

### ISSUE THREAD

**Issue by jdjshhc** [1C0D/obsidian-quick-plugin-switcher#4]
Plugins start late, like Plugin Groups

**Comment by 1C0D** [comment]
I've just watched this plugin. The level of code is way much higher than mine. But in terms of using, this is quite complex to handle and far from what I wanted, a quick access, to toggle plugins. This is one of his main features. I did something totally different, I'm not sure, if I want to copy his feature and if I'm able to do it. But on the other hand, if I do it I have to do it now, because I will have to reset datas again... If I do it, I will disable plugins when obsidian stop, and re-enable them after a delay on layout ready (he did a much more complex approach). It won't be perfect, but it should work. But it could be the source of many bugs too. That's dangerous considering my level. Should I do it? 🤔 What do you think ?

**Comment by jdjshhc** [comment]
I think it's more appropriate to follow your own interests and ideas, and don't be disturbed by me. You look at what you want to do and what you want to achieve.

**Comment by 1C0D** [comment]
ok thks for your answer. It's a good idea, if I feel it's ok, I will do it. In respect of the other plugin. Liam said it's not a problem to copy features from other plugins. At the end it's free, so it shouldn't be a problem.

**Comment by 1C0D** [comment]
ok I had a look at his code and he is using enable without saving, so if you delete his plugin, all plugins in previous groups will be deactivated. and all the structure of his plugin is done on groups first. I can add this options to each plugin or a group I will turn group name to red or kind of if the group is delayed and I will try to turn the bullet of the toggle plugin button to the same color if a plugin is delayed. with some shortcuts... this is coming when building... so I will do a new branch and test it.

**Comment by 1C0D** [comment]
Ok I did it, it took me a week

**Comment by jdjshhc** [comment]
I believe this plugin will be liked by more and more people

**Comment by 1C0D** [comment]
well good, if it's useful and working well. I have to improve another plugin I did before, "close similar tabs". It will be hard again. And then I will maybe add other tools to this one. Like opening external files to the vault in the vault, copying info in the obsidian plugin panel, where you see all plugins. Some little feature I already started before, as commands, so not adding anything to the actual UI. It was the first goal to do like a tool box and not publish one plugin for each feature. Of course, I will see this in time, and if it's relevant, add them.
